name: all_school_info
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # animated_splash_screen: ^1.1.0
  auto_route: ^2.3.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^2.5.1
  collection: ^1.15.0
  computer: ^2.0.0
  cupertino_icons: ^1.0.3

  design:
    path: packages/design
  domain:
    path: packages/domain

  firebase_messaging: ^10.0.6
  firebase_remote_config: ^0.10.0+5
  
  
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  
  flutter_redux: ^0.8.2
  google_fonts: ^2.1.0
  modal_bottom_sheet: ^2.0.0

  # firebase_auth: ^3.1.0
  # flutter_bloc: ^7.2.0
  # pull_to_refresh: ^2.0.0
  utils:
    path: packages/utils

dev_dependencies:
  auto_route_generator: ^2.3.0
  build: ^2.0.0
  build_runner: ^2.0.4
  built_value_generator: ^8.0.6
  
  flutter_test:
    sdk: flutter

  linter: ^1.10.0
  # freezed: ^0.14.2
  # get_it: ^7.2.0

dependency_overrides:
  meta: ^1.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/theme/
    - assets/splash/

flutter_intl:
  enabled: true # Disable when push
  main_locale: ru
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated
  class_name: AllSchoolInfoIntl