name: domain
description: domain
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.1
  computer: ^2.0.0
  
  firebase_auth: ^3.1.1
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  j_linter: ^0.0.6
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  rxdart: ^0.27.2

  # local
  utils:
    path: ../utils

dev_dependencies:
  build: ^2.0.0
  build_runner: ^2.0.4
  freezed: ^0.14.2
  json_serializable: ^4.1.3
  pedantic: ^1.11.0
  test: ^1.17.9