name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format -l 120 --output=none --set-exit-if-changed .

      # Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze

      - name: telegram test
        run: curl -s -X POST "https://api.telegram.org/bot1964599551:AAEl9OkJJ11C1Jizaa2TVbiKCr-CJIuCH6I/sendMessage" -d chat_id=-545357126 -d text="⛵️ test" -d parse_mode="HTML"

      # - name: Run tests
      #   run: dart test
